# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.3.0.preview2"

gem "advent_of_code_cli"
gem 'colorize'
gem 'pqueue'
gem 'pry'
gem 'rspec'
gem 'ruby-progressbar'
gem 'super_diff'
gem 'set'
